[tls]
certificates_directory = "/var/sota/"
ca_file = "root.crt"
client_certificate = "client.pem"
pkey_file = "pkey.pem"

[uptane]
metadata_path = "/var/sota/metadata"
private_key_path = "ecukey.der"
public_key_path = "ecukey.pub"

[provision]
provision_path = "/var/sota/sota_provisioning_credentials.zip"

