[tls]
certificates_directory = "/var/sota/"
ca_file = "/var/sota/token/root.crt"
client_certificate = "01"
cert_source = "pkcs11"
pkey_file = "02"
pkey_source = "pkcs11"

[p11]
module = "/usr/lib/softhsm/libsofthsm2.so"
pass = "1234"

[uptane]
metadata_path = "/var/sota/metadata"
key_source = "pkcs11"
private_key_path = "03"
public_key_path = "03"

